services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false
    
    book.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { title: ~, price.amount: ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
    
    book.text_filter:
        parent: 'planb.doctrine.orm.text_filter'
        arguments:
            $properties: { title: ~ }
        tags: [ 'api_platform.filter' ]

    book.range_filter:
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [ { price.amount: ~ } ]
        tags:  [ 'api_platform.filter' ]


#    book.range_filter:
#        parent: 'planb.doctrine.orm.range_filter'
#        arguments:
#            $properties: { title: ~ }
#        tags: [ 'api_platform.filter' ]
