version: "3.4"

# Production environment override
services:
  php:
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.dev.ini:ro
  
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  www:
    command: "yarn dev"

  admin:
    command: 'sh -c "yarn build; yarn start"'
#    command: "yarn dev"
