version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory 
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      #CORS_ALLOW_ORIGIN: "*"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:rw
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
    ports:
      - target: 8002
        published: 8002
        protocol: tcp
  
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  ###< doctrine/doctrine-bundle ###

  www:
    command: "yarn dev"
  #    ports:
  #      - target: 8002
  #        published: 5000
  #        protocol: tcp
  #  
  admin:
    command: "yarn dev"

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
