version: "3.4"

# Production environment override
services:
  whisper:
    command: uvicorn app.main:api --host 0.0.0.0 --port 8080 
  
  php:
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.dev.ini:ro
  
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  www:
    command: 'sh -c "yarn build && yarn start"'

  admin:
    command: 'sh -c "yarn build && yarn start"'
