gesdinet_jwt_refresh_token:
    refresh_token_class: App\Auth\Domain\Model\RefreshToken
    single_use: true
    return_expiration: true
    logout_firewall: main
    ttl: 2592000  #30 dias 60*60*24*30
    
