lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 86400 #1 dia
#    token_extractors:
#        # check token in a cookie
#        cookie:
#            enabled: true
#            name: auth
    
#    user_identity_field: email
