App\BookStore\Domain\Model\Tag:
    attributes:
        id:
            groups:
                - read
        name:
            groups:
                - read
                - write
        books:
            groups:
                - read
                - write
App\BookStore\Application\Input\TagInput:
    attributes:
        name:
            groups:
                - write
        books:
            groups:
                - write
